server:
  port: 8082

spring:
  application:
    name: wallet-service

  datasource:
    url: jdbc:postgresql://localhost:5432/db_wallet_service
    username: postgres
    password: postgresspassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

management:
  endpoints:
    web:
      exposure:
        include: health,info

resilience4j:
  circuitbreaker:
    instances:
      userServiceCB:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-treshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2

clients:
  user-service:
    url: http://localhost:8081

